### ISSUE TITLE
SyntaxError: invalid syntax (line 49)

### ISSUE THREAD

**Issue by CyberNaruto** [Vladimir-0001/Agechecker-Bypass#2]
I receive the following error when trying to run the script after adding the paths for the certificates:

C:\Users\Username\Downloads>python bypass.py
  File "bypass.py", line 49
    "uuid": f"{uuid}",
                         ^
SyntaxError: invalid syntax

Is there something I'm doing wrong? do i need to add/remove brackets somewhere?
![temp](https://github.com/Vladimir-0001/Agechecker-Bypass/assets/9091773/97521a3b-5c22-42f4-a594-50feaf4dbe57)

**Comment by Vladimir-0001** [comment]
please join the discord for help
